# Site settings
title: New Orleans
client:
  name: British Airways
  link: https://www.britishairways.com/en-gb/home
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Piercing brass and hot, jazz-fuelled nights on Frenchmen Street, steaming bowls of gumbo and sipping a sazerac in the Quarter, shotgun homes and decorated French mansions â€“ New Orleans is a heady concoction of spellbinding cultural pursuits.


# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/britishairwaysneworleans" # the subpath of your site, e.g. /blog/
img:     "/britishairwaysneworleans/_assets/img"
css:     "/britishairwaysneworleans/_assets/css"
js:      "/britishairwaysneworleans/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed